export const SHOW_ALL_PLACES = 'SHOW_ALL_PLACES';
export const SHOW_SEARCHED_PLACES = 'SHOW_SEARCHED_PLACES';

export const REQUEST_ALL_PLACES = 'REQUEST_ALL_PLACES';
export const RECEIVE_ALL_PLACES = 'RECEIVE_ALL_PLACES';

export const REQUEST_SEARCHED_PLACES = 'REQUEST_SEARCHED_PLACES';
export const RECEIVE_SEARCHED_PLACES = 'RECEIVE_SEARCHED_PLACES';

export const SHOW_ERROR = 'SHOW_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';

export const LOADING = 'LOADING';

export const POST_BOOK_TOUR = 'POST_BOOK_TOUR';
export const POST_BOOK_TOUR_SUCCESS = 'POST_BOOK_TOUR_SUCCESS';

export const POST_FEEDBACK = 'POST_FEEDBACK';
export const POST_FEEDBACK_SUCCESS = 'POST_FEEDBACK_SUCCESS';